### PR TITLE
Update to ember 3.7

### PR DESCRIPTION
**Pull request by snewcomer**

### CODE REVIEW

**Comment by john-griffin** [comment]
Also seeing no head template rendered under tests or in app on ember-cli `3.4.2`.

**Comment by rwjblue** [comment]
This was also recently reported to the ember-cli repo too, though I haven’t dug in yet as to why it isn’t working...

**Comment by snewcomer** [comment]
@rwjblue This should be ready for your review!

**Comment by toranb** [comment]
@rwjblue what issue/PR in ember-cli reports something similar? I've found our app is currently busted also w/ the `head.hbs has gone missing` comment

**Comment by josemarluedke** [comment]
@toranb That has been fixed on Ember CLI v3.4.3. Here is the related issue on Ember CLI: https://github.com/ember-cli/ember-cli/issues/8042

**Comment by omairrazam** [comment]
Hi all.
Any chance of merging this?
I am unable to use addon with ember 3.* versions.

There is no error and I don't see any content of head template in my page source.

Any help?

**Comment by omairrazam** [comment]
ok, sorry for that.

I just observed the we don't see ember generated tabs in page source but when I did inspect element, I had found it.

**Comment by snewcomer** [comment]
@rwjblue FYI - Taking the default travis blueprint template, removing "stage:" got the tests passing - https://github.com/ronco/ember-cli-head/pull/53/commits/eeb3120d29ec86877bd5fb76918afc603c8b1023

**Comment by josemarluedke** [comment]
What's missing to get this merged?

**Pull request merged**
